USE master;
GO
IF NOT EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME='DB_PROJETOS_MTTECHNE')
create database DB_PROJETOS_MTTECHNE;
GO

USE DB_PROJETOS_MTTECHNE;
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBCLIENTES' AND XTYPE='U')
CREATE TABLE TBCLIENTES
(	
	IDCLIENTE	INT NOT NULL IDENTITY,
	CNPJ	VARCHAR(14) NOT NULL,
	RAZAOSOCIAL	VARCHAR(50) NOT NULL,
	TELEFONE	VARCHAR(13) NOT NULL,
	ENDERECO	VARCHAR(50) NOT NULL,
	EMAIL	VARCHAR(50) NOT NULL, 
	RAMOATIVIDADES	VARCHAR(50) NOT NULL
	CONSTRAINT TB_CLIENTES_PK_IDCLIENTE PRIMARY KEY(IDCLIENTE)
);
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBSKILLS' AND XTYPE='U')
CREATE TABLE TBSKILLS
(
	IDSKILL INT NOT NULL IDENTITY,
	DESCRICAO VARCHAR(50) NOT NULL,
	NIVEL VARCHAR(20) NOT NULL
	CONSTRAINT TB_SKILL_PK_IDSKILL PRIMARY KEY(IDSKILL)
);
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBCOLABORADORES' AND XTYPE='U')
CREATE TABLE TBCOLABORADORES
(
	IDCOLABORADOR	INT NOT NULL IDENTITY,
	NOME	VARCHAR(50) NOT NULL,
	CNPJ	VARCHAR(14) NOT NULL,
	VALORHORA	FLOAT NOT NULL,
	TIPO	INT NOT NULL,
	IDSKILL INT NOT NULL,
	CONSTRAINT TB_COLABORADORES_PK_IDCOLABORADOR PRIMARY KEY(IDCOLABORADOR),
	CONSTRAINT TB_COLABORADORES_CK_TIPO CHECK (TIPO=1 OR TIPO=2),
	CONSTRAINT TB_COLABORADORES_FK_IDSKILL FOREIGN KEY (IDSKILL) REFERENCES TBSKILLS(IDSKILL)
);
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBPROJETOS' AND XTYPE='U')
CREATE TABLE TBPROJETOS
(
	IDPROJETO	INT NOT NULL IDENTITY,
	DESCRICAO	VARCHAR(50) NOT NULL,
	IDCLIENTE	INT NOT NULL,
	DATAINICIO DATETIME NOT NULL,
	DATATERMINO	DATETIME,
	NUMHORAS	INT,
	VALORPROJETO	FLOAT NOT NULL,
	VALORDESPESAS	FLOAT,
	STATUSPROJETO	BIT
	CONSTRAINT TB_PROJETOS_PK_IDPROJETO PRIMARY KEY(IDPROJETO)
	CONSTRAINT TB_PROJETOS_FK_IDCLIENTE FOREIGN KEY(IDCLIENTE) REFERENCES TBCLIENTES(IDCLIENTE)

);
GO

--IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBSKILL_COLAB' AND XTYPE='U')
--CREATE TABLE TBSKILL_COLAB
--(
--	IDSKILL_COLAB INT NOT NULL IDENTITY,
--	IDSKILL INT NOT NULL,
--	IDCOLABORADOR	INT NOT NULL
--	CONSTRAINT TB_SKILLCOLAB_PK_IDSKILL_COLAB PRIMARY KEY(IDSKILL_COLAB)
--	CONSTRAINT TB_SKILL_FK_IDSKILL FOREIGN KEY(IDSKILL) REFERENCES TBSKILLS(IDSKILL),
--	CONSTRAINT TB_COLABORADORES_FK_IDCOLABORADOR FOREIGN KEY (IDCOLABORADOR) REFERENCES TBCOLABORADORES(IDCOLABORADOR)
--)
--GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBPROJ_COLAB' AND XTYPE='U')
CREATE TABLE TBPROJ_COLAB
(
	IDPROJ_COLAB INT NOT NULL IDENTITY,
	IDCOLABORADOR INT NOT NULL,
	IDPROJETO INT NOT NULL,
	IDSKILL INT NOT NULL,
	VALORHORAPROJ_COLAB FLOAT NOT NULL
	CONSTRAINT TB_PROJCOLAB_PK_IDPROJCOLAB PRIMARY KEY(IDPROJ_COLAB)
	CONSTRAINT TB_PROJCOLAB_FK_IDCOLABORADOR FOREIGN KEY(IDCOLABORADOR) REFERENCES TBCOLABORADORES(IDCOLABORADOR),	
	CONSTRAINT TB_PROJCOLAB_FK_IDPROJETO FOREIGN KEY(IDPROJETO) REFERENCES TBPROJETOS(IDPROJETO),
	CONSTRAINT TB_PROJCOLAB_FK_IDSKILL FOREIGN KEY(IDSKILL) REFERENCES TBSKILLS(IDSKILL)
)
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TBATIVIDADES' AND XTYPE='U')
CREATE TABLE TBATIVIDADES
(
	IDATIVIDADE INT NOT NULL IDENTITY,
	HORAINICIO	DATETIME NOT NULL,
	HORAFIM DATETIME NOT NULL,
	IDPROJ_COLAB INT NOT NULL
	CONSTRAINT TB_ATIVIDADES_PK_IDATIVIDADE PRIMARY KEY(IDATIVIDADE)
	CONSTRAINT TB_ATIVIDADES_FK_IDPROJ_COLAB FOREIGN KEY(IDPROJ_COLAB) REFERENCES TBPROJ_COLAB(IDPROJ_COLAB)
)
GO

