//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.GestaoProjetos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Atividade
    {
        [Display(Name = "Cód. Atividade:")]
        public int IDATIVIDADE { get; set; }
        [Required]
        [Display(Name = "Hr. Inicio:")]
        [DataType(DataType.Time)]
        public System.DateTime HoraInicio { get; set; }
        [Required]
        [Display(Name = "Hr. Fim:")]
        [DataType(DataType.Time)]
        public System.DateTime HoraFim { get; set; }
        [Required]
        [Display(Name = "Projeto - Colaborador:")]
        public int IDPROJ_COLAB { get; set; }

        public virtual ProjetosColaborador ProjetoColaborador { get; set; }
    }
}
