//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.GestaoProjetos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CadProjeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadProjeto()
        {
            this.ProjetoColaborador = new HashSet<ProjetosColaborador>();
        }

        public int IDPROJETO { get; set; }
        [Required]
        [Display(Name = "Proj. Descrição:")]
        public string Descricao { get; set; }
        [Required]
        [Display(Name = "Cliente:")]
        public int IDCLIENTE { get; set; }
        [Required]
        [Display(Name = "Dt. Inicio:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DataInicio { get; set; }
        [Display(Name = "Dt. Termino:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DataTermino { get; set; }
        [Display(Name = "Núm. Horas:")]
        public Nullable<int> NumHoras { get; set; }
        [Required]
        [Display(Name = "Orçamento:")]
        [DataType(DataType.Currency)]
        public double ValorProjeto { get; set; }
        [Display(Name = "Despesas:")]
        [DataType(DataType.Currency)]
        public Nullable<double> ValorDespesas { get; set; }
        [Required]
        [Display(Name = "Situação:")]
        public int Status { get; set; }
        [Required]
        [Display(Name = "Tipo de Escopo:")]
        public int Escopo { get; set; }

        public virtual Cliente ClienteInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjetosColaborador> ProjetoColaborador { get; set; }
    }
}
