//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.GestaoProjetos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colaborador()
        {
            this.ProjetoColaborador = new HashSet<ProjetosColaborador>();
        }

        [Display(Name = "Colaborador:")]
        public int IDCOLABORADOR { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Colaborador:")]
        public string Nome { get; set; }
        [Required]        
        [DataType(DataType.Currency)]
        [Display(Name = "Valor-Hora:")]
        public double ValorHora { get; set; }
        [Required]
        [Display(Name = "Tipo Doc.:")]
        public int Tipo { get; set; }
        [Required]
        [Display(Name = "Skill:")]
        public int IDSKILL { get; set; }        
        [Display(Name = "Telefone:")]
        public string Telefone { get; set; }
        [StringLength(50)]
        [Display(Name = "E-Mail:")]
        public string Email { get; set; }
        [Required]
        [StringLength(14, MinimumLength = 11)]
        [Display(Name = "Documento:")]
        public string Documento { get; set; }
        [Required]
        [Display(Name = "Situação:")]
        public int Status { get; set; }

        public virtual Skill SkillInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjetosColaborador> ProjetoColaborador { get; set; }
    }
}
