//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.GestaoProjetos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoConnection : DbContext
    {
        public ProjetoConnection()
            : base("name=ProjetoConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atividade> Atividades { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Colaborador> Colaboradores { get; set; }
        public virtual DbSet<ProjetosColaborador> Proj_Colaboradores { get; set; }
        public virtual DbSet<CadProjeto> CadProjetos { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
    }
}
