//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.GestaoProjetos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjetosColaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjetosColaborador()
        {
            this.Atividade = new HashSet<Atividade>();
        }

        public int IDPROJ_COLAB { get; set; }
        [Display(Name = "Projeto:")]
        [Required]
        public int IDPROJETO { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Val. Hora no Projeto:")]
        public double ValorHoraProjColab { get; set; }
        [Display(Name = "Colaborador:")]
        [Required]
        public int IDCOLABORADOR { get; set; }
        [Display(Name = "Skill:")]
        [Required]
        public int IDSKILL { get; set; }
        [DataType(DataType.Currency)]    
        public double ValorColaborador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividade> Atividade { get; set; }
        public virtual CadProjeto Projeto { get; set; }
        public virtual Colaborador ColaboradorInfo { get; set; }
        public virtual Skill SkillInfo { get; set; }
    }
}
