//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.GestaoProjetos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.ColaboradorInfo = new HashSet<Colaborador>();
            this.ProjetoColaborador = new HashSet<ProjetosColaborador>();
        }


        [Display(Name = "Skill:")]
        public int IDSKILL { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Descricão:")]
        public string Descricao { get; set; }
        [Required]
        [StringLength(20)]
        [Display(Name = "Nível:")]
        public string Nivel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colaborador> ColaboradorInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjetosColaborador> ProjetoColaborador { get; set; }
    }
}
